runtime: nodejs12

instance_class: F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: public/stylesheets
  secure: always

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
